chore: update openshell script
Signed-off-by: Abhishek Rai <rai.abhishek90@gmail.com>

diff --git a/.local/bin/kubectl-openshell b/.local/bin/kubectl-openshell
--- a/.local/bin/kubectl-openshell
+++ b/.local/bin/kubectl-openshell
@@ -1,11 +1,50 @@
 #!/usr/bin/env bash
 
-if [ "$#" -lt 1 ]; then
-  echo "Usage: kubectl openshell <pod-name> [-n <namespace>]"
-  exit 1
+# Initialize variables
+pod_name=""
+namespace="default"
+shell="bash"
+
+# Function to display usage
+usage() {
+    echo "Usage: $0 <pod-name> [-n namespace] [-s shell]"
+    echo "  pod-name: (required) Name of the pod"
+    echo "  -n: (optional) Namespace of the pod (default: default)"
+    echo "  -s: (optional) Shell to use (default: /bin/sh)"
+    exit 1
+}
+
+# Parse command-line arguments
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -n)
+            namespace="$2"
+            shift 2
+            ;;
+        -s)
+            shell="$2"
+            shift 2
+            ;;
+        -*)
+            echo "Unknown option: $1"
+            usage
+            ;;
+        *)
+            if [ -z "$pod_name" ]; then
+                pod_name="$1"
+            else
+                echo "Too many arguments"
+                usage
+            fi
+            shift
+            ;;
+    esac
+done
+
+# Check if pod name is provided
+if [ -z "$pod_name" ]; then
+    echo "Error: Pod name is required"
+    usage
 fi
 
-POD_NAME=$1
-NAMESPACE=${2:-default}
-
-kubectl exec -it "$POD_NAME" -n "$NAMESPACE" -- /usr/bin/env bash
+kubectl exec -it "$pod_name" -n "$namespace" -- "/usr/bin/$shell"
